on:
  push:
    branches:
    - main
    tags:
    - '!*'
  pull_request:
    branches:
    - main

name: Main
permissions:
  contents: read
jobs:
  build_linux:
    name: Build Linux
    container:
      image: ubuntu:22.04
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false
      matrix:
        compiler: [ gcc, clang ]
        include:
          - compiler: gcc
            cxx_compiler: g++
            compiler_flags: -Wall -Wextra -Werror -Wno-builtin-declaration-mismatch
            packages: gcc g++
          - compiler: clang
            cxx_compiler: clang++
            compiler_flags: -Wall -Wextra -Werror -Wno-unused-function -Wno-incompatible-library-redeclaration
            packages: clang

    steps:
    - uses: actions/checkout@v5

    - name: Install dependencies
      run: |
        set -e
        export DEBIAN_FRONTEND=noninteractive
        apt-get update -y
        apt-get install -y autoconf git libtool make pkg-config ${{ matrix.packages }}

    - name: Configure ImageMagick
      env:
        CC: ${{ matrix.compiler }}
        CXX: ${{ matrix.cxx_compiler }}
        CFLAGS: ${{ matrix.compiler_flags }}
        CXXFLAGS: ${{ matrix.compiler_flags }}
      run: |
        autoreconf -fiv
        ./configure --with-quantum-depth=16 --enable-hdri=no --without-perl --prefix=/usr

    - name: Build ImageMagick
      run: |
        make

    - name: Test ImageMagick
      run: |
        make check || exit_code=$?
        if [ "$exit_code" != "0" ] ; then cat ./test-suite.log ; fi
        exit $exit_code

    - name: Install ImageMagick
      run: |
        make install

  
